parameters:
    multiverse_components_matrix.form_type.matrix.class: Multiverse\Components\MatrixBundle\Form\Type\Matrix\MatrixType
    multiverse_components_matrix.form_type.matrix_row.class: Multiverse\Components\MatrixBundle\Form\Type\Matrix\MatrixRowType
services:

# Example matrix config
#    multiverse_components_matrix.form_type.matrix.name_value:
#        class: Multiverse\Components\MatrixBundle\Form\Type\Matrix\MatrixType
#        calls:
#          - [setName, ['name_value']]
#          - [addColumn, ['name', null, {}]]
#          - [addColumn, ['value', null, {}]]
#        tags:
#          - { name: form.type, alias: name_value }

    multiverse_components_matrix.form_type.matrix_row:
        class: %multiverse_components_matrix.form_type.matrix_row.class%
        tags:
          - { name: form.type, alias: matrix_row }


    multiverse_components_matrix.twig.extension:
        class: Multiverse\Components\MatrixBundle\Twig\MatrixTwigExtension
        tags:
            -  { name: 'twig.extension' }
